services:
  - type: web
    name: bonid
    env: ruby
    plan: free
    buildCommand: |
      bundle install
      yarn install
      bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
    autoDeploy: true
    branch: main
    region: oregon
