services:
  - type: web
    name: bonid
    env: ruby
    plan: free
    branch: main
    region: oregon
    buildCommand: |
      bundle install --without development test
      yarn install --frozen-lockfile
      bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false  # You'll set this in the Render dashboard
      - key: RAILS_ENV
        value: production
    autoDeploy: true
