# frozen_string_literal: true

module Admin
  class PartnerAdminMailer < VerifyemMailer
    default from: "noreply@verifyem.ht"

    # ------------------------------------------------------------
    # PARTNER INVITATION (Admin or Officer)
    # ------------------------------------------------------------
    # Args:
    #   partner: Partner record
    #   email:   String (recipient)
    #   invite_url: String (generated by PartnerSetupService)
    #
    def invite(partner:, email:, invite_url:)
      @partner = partner
      @invite_url = invite_url

      mail(
        to: email,
        subject: "You're invited to the BonID Partner Portal – #{@partner.name}"
      )
    end

    # ------------------------------------------------------------
    # PARTNER REJECTION
    # ------------------------------------------------------------
    def rejected(partner:)
      @partner = partner

      mail(
        to: partner.email,
        subject: "BonID Partner Application – Rejected"
      )
    end
  end
end
